/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.lomolith.seqeunce;

import com.lomolith.sequence.LetterPairSimilarity;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author mittens
 */
public class LetterPairSimilarityTest {
    
    public LetterPairSimilarityTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }

    // TODO add test methods here.
    // The methods must be annotated with annotation @Test. For example:
    //
    @Test
    public void hello() {
        String s = "TCCGTGAGGCTGGTGTTTTATTAGTCTTGGTCCCAGTGCTGCAGGTGTGGGCTGGGGAGTGCCTGAGGGAGGGGCCTCTGCTTGGGACCCTTCCTGCCTGGGCGAGGGGCTGAGTCCCTCCTGCCGCCCGGGCTGGGCCCCAGGTACCTGGCGAACAAAGGGACCCTGAAATTGCCGCCTTTCCCCTGCCTCTTGGGCTCTGCATATGATTTCAGCCAATCCCTGCTGCCCAGCCTCGCCCACCCGCTTCTGGGGCCACCCCCGCGTTAAGCAGGGCTGTGCAGCATGGGGGTCCTGTTCTCATTCAGCCACCGGCACGGCCACCCCAGTGTGATTCCTCAGCAGCCACACAGAAGACAGATGGTCCATAGGAGACTCAGAAACAGAGAAGCCTCACGCCAGGTCCACAGAGGCACCCACGCCCGCCAAAAGGATGCCACGCACTCACCCTGCCCTCTGGGGAGCACAGTGGGAGTCCAGGACACCGCCTTGGATGGGGTGAGGCTCCGTCTGTGACCTCAGAAAGTCAGTCTGGGGCTGGACTTGACATGGGAAACAGAATAAAACTGCCTGTCCACCTGAGCTTGCCGCCCTAAAAATCCCTGACATGATACAGAAGTCAGTGCTGACAGAGGGCCTGCTACCCCCAGTGACCCTGCCGGTGGGGTCTCAACCCACCCACTTCTTCTGGAGCAGCCGGTCACAGCTGTGGTCCTGCTGGCGCACACGGGTATGAGACCCTAAAACACACAGCGACTGCACAGTGCAACCCTGCATATCCCATTTGGGTACAAGTTTCATTACAGGAAGAAACACGGGGAGGGACCCCAGAGCAGCTCACGCGTGGGTACCCTCCGCTGTGTTAGCGTCCCGGCCCTCACACGGCACCCAGGCCTCGTTGGGGCAAGGCCTTGTGCAGACACGGTGGGATCTGCATGTGCACTGGGGCCTGTGCCTGGGCTGCTGCTCCCCGGCCACCGGTGTCAGGATCTCCAGGACCCCCATGAGTGGTCAGTGGAGCAGAGATGGCACAGACGCCAGCGACCTGGGTCATTCTCTACCTGGGATGTGGGACCCCAGAGACCATGCTGTGGGTCTTTATCTGCCTCTTCATGCAGGAGCAGGTGCGACCCCCGCCTGCCCCAGCCATGAGGCTCTGTCACAGGGGACCTCTGTGGCACCCTGTGCTGCAGGCAAGGCCTTAGGACAGATGCCACGCCACTGTCCAGGAGACTGTCTCCTGAGACTGACCTCCCCTTGCACTGGGCAATGTCTGCTGAAGATAAGGACGTCTTCACTGGGCCAGGCCTGGAGTTCTCCCAGATCGTGAGCTTTCCTCTCTCTGATGAAGAGGATACCTGTGGTCAAACTCCTACAGAGCACTGGGGACAGGAAGGCAGGCAGAGTCCCACCTGGGCAGGTGGTAGGAGTGGAAGGAGCAGGCAGGCAGCAGGGCTGCCCAGGGCTAGGAGTCTGGCTGTGAGCAGGGCCCACCCTCCCCTGGACACAATGGAGGACCCCGTGTGTGGTTTTcactgactgagcacctatctcgtgccagacatgtgggattgccggtgaattaacaaaagccctgctctcagggggctcccatcccagCACATACACCGTCACATCTGGGGTCCAGCCTGGACCCCCCCATGCAGTTGGAGAGGGTCTCAGAACCAGGTCTGAGAACAGCAACTTCCAGCCACGGCACCCCACCCCTCCCCAGCTGGCCTGGGCTCCAGCTCCTCGCACCTGAGGCTGCCTGTGCAGGGCCCCCGGCTGGTGCCCCTCTCCTCTGAAGCTCGGGGGTCGCCACAGCCTGGCACCCTCATCGGGCCTGTTACGCACGTTCTGGT";
        System.out.println(s.length());
        String c ="TGCACACGGCTCCCATGCGTTGTCTTCCGAGCGTCAGGCCGCCCCTACCCGTGCTTTCTGCTCTGCAGACCCTCTTCCTAGACCTCCGTCCTTTGTCCCATCGCTGCCTTCCCCTCAAGCTCAGGGCCAAGCTGTCCGCCAACCTCGGCTCCTCCGGGCAGCCCTCGCCCGGGGTGCGCCCCGGGGCAGGACCCCCAGCCCACGCCCAGGGCCCGCCCCTGCCCTCCAGCCCTACGCCTTGACCCGCTTTCCTGCGTCTCTCAGCCTACCTGACCTTGTCTTTACCTCTGTGGGCAGCTCCCTTGTGATCTGCTTAGTTCCCACCCCCCTTTAAGAATTCAATAGAGaagccagacgcaaaactacagatatcgtatgagtccagttttgtgaagtgcctagaatagtcaaaattcacagagacagaagcagtggtcgccaggaatggggaagcaaggcggagttgggcagctcgtgttcaatggg";
        System.out.println(c.length());
        System.out.println(LetterPairSimilarity.compareStrings(s, c.toUpperCase()));
        
        System.out.println(LetterPairSimilarity.compareStrings("TOTAL","ATOLT"));
    }
    
    
}
